spring:
  main:
    banner-mode: "off"

  datasource:
    url: jdbc:h2:~/spring-boot-h2
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    show-sql: true

  h2:
    console:
      enabled: true