spring:
  datasource:
      url: jdbc:h2:~/spring-boot-h2
      username: sa
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

logging:
  file:
    name: log/boot.log
  level:
    root: info
    com.yejianfengblue.spring: info
